- name: Kerberos and OpenAFS client installation
  hosts: all
  roles:
    - role: kerberos-client
      kerberos_realm: 'OPENSTACK.ORG'
      kerberos_admin_server: 'kdc.openstack.org'
      kerberos_kdcs:
        - kdc01.openstack.org
        - kdc02.openstack.org

    - role: openafs-client
