- name: Kerberos and OpenAFS client installation
  hosts: all
  roles:
    - role: kerberos-client
      realm: 'OPENSTACK.ORG'
      admin_server: 'kdc.openstack.org'
      kdcs:
        - kdc01.openstack.org
        - kdc02.openstack.org

    - role: openafs-client
