- hosts: all
  roles:
    - check-python-release
    - build-python-release
    - ensure-twine
  post_tasks:
    - name: Run twine check on python dist tarball
      command: "{{ pypi_twine_executable }} check dist/*"
      args:
        chdir: "{{ zuul.project.src_dir }}"
