- hosts: all
  roles:
    - role: prepare-docs-for-afs
      when: zuul_success | bool
    - role: write-root-marker
      when: zuul_success | bool
    - role: fetch-sphinx-output
      sphinx_output_suffix: "/"
      zuul_executor_dest: "{{ zuul.executor.work_root }}/artifacts"
      when: zuul_success | bool

- hosts: localhost
  roles:
    - role: create-afs-token
      when: zuul_success | bool
    - role: upload-afs
      afs_target: "{{ afs.path }}/project-deploy-guide/{{ zuul.project.short_name }}"
      when: zuul_success | bool
    - role: destroy-afs-token
      when: zuul_success | bool
