- hosts: localhost
  roles:
    - role: create-afs-token
      when: zuul_success | bool
    - role: upload-afs
      afs_target: "{{ afs.path }}/infra/{{ zuul.project.short_name }}"
      when: zuul_success | bool
    - role: destroy-afs-token
      when: zuul_success | bool
