- hosts: localhost
  tasks:
    - block:
        - name: Create AFS token
          include_role:
            name: create-afs-token
        # NOTE(ianw): the upload-afs role is somewhat structured
        # around uploading docs, and requires a .root-marker file,
        # etc.  In this case, we just want the whole directory
        # verbatim.
        - name: Upload contents of the artifacts folder
          synchronize:
            src: "{{ zuul.executor.work_root }}/artifacts/"
            dest: "/afs/.openstack.org/project/tarballs.opendev.org/{{ zuul.project.name}}/"
            # can't set group permissions on AFS; see upload-afs role
            archive: false
            perms: true
            times: true
            recursive: true
            rsync_opts:
              - '--safe-links'
              - '--delete-after'
        - name: Destroy AFS token
          include_role:
            name: destroy-afs-token
      when: zuul_success | bool
