- hosts: all
  roles:
    - role: write-root-marker
      when: zuul_success | bool
    - role: fetch-sphinx-output
      zuul_executor_dest: "{{ zuul.executor.work_root }}/artifacts"
      when: zuul_success | bool

- hosts: localhost
  roles:
    - role: create-afs-token
      when: zuul_success | bool
    - role: upload-afs
      afs_target: "{{ afs.path }}/api-ref/placement"
      when: zuul_success | bool
    - role: destroy-afs-token
      when: zuul_success | bool
