- hosts: all
  roles:
    - role: fetch-tox-output
      tox_envlist: releasenotes
    - role: write-root-marker
      root_marker_dir: "{{ zuul.project.src_dir }}/releasenotes/build/html/"
    - role: fetch-sphinx-output
      sphinx_output_src: "{{ zuul.project.src_dir }}/releasenotes/build/html/"
      zuul_executor_dest: "{{ zuul.executor.work_root }}/artifacts"

- hosts: localhost
  roles:
    - create-afs-token
    - role: upload-afs
      afs_target: "{{ afs.path }}/releasenotes/{{ zuul.project.short_name }}"
    - destroy-afs-token
