- hosts: localhost
  roles:
    - prepare-docs-for-afs
    - role: fetch-tox-output
      tox_envlist: releasenotes
    - role: fetch-sphinx-output
      sphinx_output_src: "{{ zuul.project.src_dir }}/doc/build/html/"
      zuul_executor_dest: "{{ zuul.executor.work_root }}/artifacts"
    - create-afs-token
    - role: upload-afs
      afs_target: "{{ afs.path }}/releasenotes/{{ zuul.project.short_name }}"
    - destroy-afs-token
