- hosts: all
  pre_tasks:

    # This is tempoarary until v2 is gone and we can rework things
    - name: Add origin remote to enable notes fetching
      command: "git remote add origin https://{{ item.canonical_name }}"
      args:
        chdir: "{{ ansible_user_dir }}/src/{{ item.canonical_name }}"
      with_items: "{{ zuul._projects.values() }}"

  roles:
    - legacy-copy-project-config-scripts
    - add-sshkey
    - add-launchpad-credentials
