dashboard:
  title: 'AFS'
  rows:
    - title: Description
      height: 100px
      panels:
        - title: Description
          content: |
            **This dashboard is managed by [Grafyaml](http://docs.openstack.org/infra/system-config/grafyaml.html).**

            If you would like to make changes to this dashboard, please see the grafana directory in [project-config](https://git.openstack.org/cgit/openstack-infra/project-config/tree/grafana/afs.yaml).
          type: text

    - title: Partitions
      height: 100px
      showTitle: true
      height: 150px
      panels:
        - title: "afs01.dfw /vicepa used"
          span: 3
          sparkline:
            full: true
            show: true
          thresholds: "0,90,95"
          format: percentunit
          targets:
            - target: "stats.gauges.afs.afs01_dfw_openstack_org.part.vicepa.total"
              refId: "A"
              hide: "true"
            - target: "divideSeries(stats.gauges.afs.afs01_dfw_openstack_org.part.vicepa.used, #A)"
              refId: "B"
              hide: "false"
          type: singlestat
          valueName: current

        - title: "afs02.dfw /vicepa used"
          span: 3
          sparkline:
            full: true
            show: true
          thresholds: "0,90,95"
          format: percentunit
          targets:
            - target: "stats.gauges.afs.afs02_dfw_openstack_org.part.vicepa.total"
              refId: "A"
              hide: "true"
            - target: "divideSeries(stats.gauges.afs.afs02_dfw_openstack_org.part.vicepa.used, #A)"
              refId: "B"
              hide: "false"
          type: singlestat
          valueName: current

        - title: "afs01.ord /vicepa used"
          span: 3
          sparkline:
            full: true
            show: true
          thresholds: "0,90,95"
          format: percentunit
          targets:
            - target: "stats.gauges.afs.afs01_ord_openstack_org.part.vicepa.total"
              refId: "A"
              hide: "true"
            - target: "divideSeries(stats.gauges.afs.afs01_ord_openstack_org.part.vicepa.used, #A)"
              refId: "B"
              hide: "false"
          type: singlestat
          valueName: current
