dashboard:
  title: Ceph Failure Rate
  rows:
    - title: Description
      height: 100px
      panels:
        - title: Description
          content: |
            **This dashboard is managed by [Grafyaml](http://docs.openstack.org/infra/system-config/grafyaml.html).**

            If you would like to make changes to this dashboard, please see the grafana directory in [project-config](https://git.openstack.org/cgit/openstack-infra/project-config/tree/grafana/ceph.yaml).
          type: text
    - title: Graphs
      height: 320px
      panels:
        - title: Platform Tempest Full Failure Rates (Check queue)
          span: 4
          targets:
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.pipeline.check.job.tempest-full.FAILURE),sum(stats_counts.zuul.pipeline.check.job.tempest-full.{SUCCESS,FAILURE})),'24hours'), 'tempest-full')
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.pipeline.check.job.devstack-plugin-ceph-tempest.FAILURE),sum(stats_counts.zuul.pipeline.check.job.devstack-plugin-ceph-tempest.{SUCCESS,FAILURE})),'24hours'), 'devstack-plugin-ceph-tempest')
          type: graph
