dashboard:
  title: Horizon Failure Rate
  rows:
    - title: Description
      height: 100px
      panels:
        - title: Description
          content: |
            **This dashboard is managed by [Grafyaml](http://docs.openstack.org/infra/system-config/grafyaml.html).**

            If you would like to make changes to this dashboard, please see the grafana directory in [project-config](https://opendev.org/openstack/project-config/src/grafana/horizon.yaml).
          type: text
    - title: Graphs
      height: 320px
      panels:
        - title: npm test Failure Rates (Gate queue)
          span: 4
          targets:
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.tenant.openstack.pipeline.gate.project.opendev_org.openstack_horizon.master.job.nodejs-npm-run-test.FAILURE),sum(stats_counts.zuul.tenant.openstack.pipeline.gate.project.opendev_org.openstack_horizon.master.job.nodejs-npm-run-test.{SUCCESS,FAILURE})),'24hours'), 'nodejs4-npm-run-test')
          type: graph
        - title: Unit Tests Failure Rates (Check queue)
          span: 4
          targets:
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.tenant.openstack.pipeline.check.project.opendev_org.openstack_horizon.master.job.openstack-tox-py27.FAILURE),sum(stats_counts.zuul.tenant.openstack.pipeline.check.project.opendev_org.openstack_horizon.master.job.openstack-tox-py27.{SUCCESS,FAILURE})),'24hours'), 'openstack-tox-py27')
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.tenant.openstack.pipeline.check.project.opendev_org.openstack_horizon.master.job.openstack-tox-py35.FAILURE),sum(stats_counts.zuul.tenant.openstack.pipeline.check.project.opendev_org.openstack_horizon.master.job.openstack-tox-py35.{SUCCESS,FAILURE})),'24hours'), 'openstack-tox-py35')
          type: graph
        - title: Unit Tests Failure Rates (Gate queue)
          span: 4
          targets:
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.tenant.openstack.pipeline.gate.project.opendev_org.openstack_horizon.master.job.openstack-tox-py27.FAILURE),sum(stats_counts.zuul.tenant.openstack.pipeline.gate.project.opendev_org.openstack_horizon.master.job.openstack-tox-py27.{SUCCESS,FAILURE})),'24hours'), 'openstack-tox-py27')
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.tenant.openstack.pipeline.gate.project.opendev_org.openstack_horizon.master.job.openstack-tox-py35.FAILURE),sum(stats_counts.zuul.tenant.openstack.pipeline.gate.project.opendev_org.openstack_horizon.master.job.openstack-tox-py35.{SUCCESS,FAILURE})),'24hours'), 'openstack-tox-py35')
          type: graph
        - title: Tempest Failure Rates (Check queue)
          span: 4
          targets:
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.tenant.openstack.pipeline.check.project.opendev_org.openstack_horizon.master.job.horizon-dsvm-tempest-plugin.FAILURE),sum(stats_counts.zuul.tenant.openstack.pipeline.check.project.opendev_org.openstack_horizon.master.job.horizon-dsvm-tempest-plugin.{SUCCESS,FAILURE})),'24hours'), 'horizon-dsvm-tempest-plugin')
          type: graph
        - title: Tempest Failure Rates (Gate queue)
          span: 4
          targets:
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.tenant.openstack.pipeline.gate.project.opendev_org.openstack_horizon.master.job.horizon-dsvm-tempest-plugin.FAILURE),sum(stats_counts.zuul.tenant.openstack.pipeline.gate.project.opendev_org.openstack_horizon.master.job.horizon-dsvm-tempest-plugin.{SUCCESS,FAILURE})),'24hours'), 'horizon-dsvm-tempest-plugin')
          type: graph
