dashboard:
  title: Networking BaGPipe Failure Rates
  rows:
    - title: Description
      height: 100px
      panels:
        - title: Description
          content: |
            **This dashboard is managed by [Grafyaml](http://docs.openstack.org/infra/system-config/grafyaml.html).**

            If you would like to make changes to this dashboard, please see the grafana directory in [project-config](https://git.openstack.org/cgit/openstack-infra/project-config/tree/grafana/networking-bagpipe.yaml).
          type: text
    - title: Graphs
      height: 320px
      panels:
        - title: Unit Test Failure Rates (Check queue)
          span: 4
          targets:
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.pipeline.check.job.gate-networking-bagpipe-python27-db-ubuntu-xenial.FAILURE),sum(stats_counts.zuul.pipeline.check.job.gate-networking-bagpipe-python27-db-ubuntu-xenial.{SUCCESS,FAILURE})),'24hours'), 'gate-networking-bagpipe-python27-db-ubuntu-xenial')
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.pipeline.check.job.gate-networking-bagpipe-python35-db-ubuntu-xenial.FAILURE),sum(stats_counts.zuul.pipeline.check.job.gate-networking-bagpipe-python35-db-ubuntu-xenial.{SUCCESS,FAILURE})),'24hours'), 'gate-networking-bagpipe-python35-db-ubuntu-xenial')
          type: graph
        - title: Unit Test Failure Rates (Gate queue)
          span: 4
          targets:
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.pipeline.gate.job.gate-networking-bagpipe-python27-db-ubuntu-xenial.FAILURE),sum(stats_counts.zuul.pipeline.gate.job.gate-networking-bagpipe-python27-db-ubuntu-xenial.{SUCCESS,FAILURE})),'24hours'), 'gate-networking-bagpipe-python27-db-ubuntu-xenial')
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.pipeline.gate.job.gate-networking-bagpipe-python35-db-ubuntu-xenial.FAILURE),sum(stats_counts.zuul.pipeline.gate.job.gate-networking-bagpipe-python35-db-ubuntu-xenial.{SUCCESS,FAILURE})),'24hours'), 'gate-networking-bagpipe-python35-db-ubuntu-xenial')
          type: graph
        - title: Tempest Failure Rates (Check queue)
          span: 4
          targets:
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.pipeline.check.job.gate-tempest-dsvm-networking-bgpvpn-bagpipe.FAILURE),sum(stats_counts.zuul.pipeline.check.job.gate-tempest-dsvm-networking-bgpvpn-bagpipe.{SUCCESS,FAILURE})),'24hours'), 'gate-tempest-dsvm-networking-bgpvpn-bagpipe')
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.pipeline.check.job.gate-tempest-dsvm-networking-bagpipe-full-nv.FAILURE),sum(stats_counts.zuul.pipeline.check.job.gate-tempest-dsvm-networking-bagpipe-full-nv.{SUCCESS,FAILURE})),'24hours'), 'gate-tempest-dsvm-networking-bagpipe-full-nv')
          type: graph
        - title: Tempest Failure Rates (Gate queue)
          span: 4
          targets:
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.pipeline.gate.job.gate-tempest-dsvm-networking-bgpvpn-bagpipe.FAILURE),sum(stats_counts.zuul.pipeline.gate.job.gate-tempest-dsvm-networking-bgpvpn-bagpipe.{SUCCESS,FAILURE})),'24hours'), 'gate-tempest-dsvm-networking-bgpvpn-bagpipe')
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.pipeline.gate.job.gate-tempest-dsvm-networking-bagpipe-full-nv.FAILURE),sum(stats_counts.zuul.pipeline.gate.job.gate-tempest-dsvm-networking-bagpipe-full-nv.{SUCCESS,FAILURE})),'24hours'), 'gate-tempest-dsvm-networking-bagpipe-full-nv')
          type: graph
        - title: Periodic jobs
          span: 4
          targets:
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.pipeline.periodic.job.periodic-networking-bagpipe-py35-with-neutron-lib-master.FAILURE),sum(stats_counts.zuul.pipeline.periodic.job.periodic-networking-bagpipe-py35-with-neutron-lib-master.{SUCCESS,FAILURE})),'24hours'), 'periodic-networking-bagpipe-py35-with-neutron-lib-master')
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.pipeline.periodic-stable.job.periodic-networking-bagpipe-python27-newton.FAILURE),sum(stats_counts.zuul.pipeline.periodic-stable.job.periodic-networking-bagpipe-python27-newton.{SUCCESS,FAILURE})),'24hours'), 'periodic-networking-bagpipe-python27-newton')
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.pipeline.periodic-stable.job.periodic-networking-bagpipe-python27-mitaka.FAILURE),sum(stats_counts.zuul.pipeline.periodic-stable.job.periodic-networking-bagpipe-python27-mitaka.{SUCCESS,FAILURE})),'24hours'), 'periodic-networking-bagpipe-python27-mitaka')
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.pipeline.periodic-stable.job.periodic-networking-bagpipe-python27-liberty.FAILURE),sum(stats_counts.zuul.pipeline.periodic-stable.job.periodic-networking-bagpipe-python27-liberty.{SUCCESS,FAILURE})),'24hours'), 'periodic-networking-bagpipe-python27-liberty')
          type: graph
