dashboard:
  title: Neutron FWaaS Failure Rates
  rows:
    - title: Description
      height: 100px
      panels:
        - title: Description
          content: |
            **This dashboard is managed by [Grafyaml](http://docs.openstack.org/infra/system-config/grafyaml.html).**

            If you would like to make changes to this dashboard, please see the grafana directory in [project-config](https://git.openstack.org/cgit/openstack-infra/project-config/tree/grafana/neutron-fwaas.yaml).
          type: text
    - title: Graphs
      height: 320px
      panels:
        - title: Unit Test Failure Rates (Check queue)
          span: 4
          targets:
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.pipeline.check.job.gate-neutron-fwaas-python27{,-ubuntu-trusty,-ubuntu-xenial}.FAILURE),sum(stats_counts.zuul.pipeline.check.job.gate-neutron-fwaas-python27{,-ubuntu-trusty,-ubuntu-xenial}.{SUCCESS,FAILURE})),'24hours'), 'gate-neutron-fwaas-python27')
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.pipeline.check.job.gate-neutron-fwaas-python34.FAILURE),sum(stats_counts.zuul.pipeline.check.job.gate-neutron-fwaas-python34.{SUCCESS,FAILURE})),'24hours'), 'gate-neutron-fwaas-python34')
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.pipeline.check.job.gate-neutron-fwaas-python35.FAILURE),sum(stats_counts.zuul.pipeline.check.job.gate-neutron-fwaas-python35.{SUCCESS,FAILURE})),'24hours'), 'gate-neutron-fwaas-python35')
          type: graph
    - title: Graphs
      height: 320px
      panels:
        - title: Unit Test Failure Rates (Gate queue)
          span: 4
          targets:
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.pipeline.gate.job.gate-neutron-fwaas-python27{,-ubuntu-trusty,-ubuntu-xenial}.FAILURE),sum(stats_counts.zuul.pipeline.gate.job.gate-neutron-fwaas-python27{,-ubuntu-trusty,-ubuntu-xenial}.{SUCCESS,FAILURE})),'24hours'), 'gate-neutron-fwaas-python27')
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.pipeline.gate.job.gate-neutron-fwaas-python34.FAILURE),sum(stats_counts.zuul.pipeline.gate.job.gate-neutron-fwaas-python34.{SUCCESS,FAILURE})),'24hours'), 'gate-neutron-fwaas-python34')
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.pipeline.gate.job.gate-neutron-fwaas-python35.FAILURE),sum(stats_counts.zuul.pipeline.gate.job.gate-neutron-fwaas-python35.{SUCCESS,FAILURE})),'24hours'), 'gate-neutron-fwaas-python35')
          type: graph
    - title: Graphs
      height: 320px
      panels:
        - title: Periodic jobs
          span: 4
          targets:
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.pipeline.periodic.job.periodic-neutron-fwaas-py34-with-neutron-lib-master.FAILURE),sum(stats_counts.zuul.pipeline.periodic.job.periodic-neutron-fwaas-py34-with-neutron-lib-master.{SUCCESS,FAILURE})),'24hours'), 'periodic-neutron-fwaas-py34-with-neutron-lib-master')
          type: graph
    - title: Graphs
      height: 320px
      panels:
        - title: Integrated Failure Rates (Gate queue)
          span: 4
          targets:
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.pipeline.gate.job.gate-tempest-dsvm-neutron-fwaas.FAILURE),sum(stats_counts.zuul.pipeline.gate.job.gate-tempest-dsvm-neutron-fwaas.{SUCCESS,FAILURE})),'24hours'), 'gate-tempest-dsvm-neutron-fwaas')
          type: graph
