dashboard:
  title: Neutron Failure Rate
  rows:
    - title: Description
      height: 100px
      panels:
        - title: Description
          content: |
            **This dashboard is managed by [Grafyaml](http://docs.openstack.org/infra/system-config/grafyaml.html).**

            If you would like to make changes to this dashboard, please see the grafana directory in [project-config](https://git.openstack.org/cgit/openstack-infra/project-config/tree/grafana/neutron.yaml).
          type: text
    - title: Graphs
      height: 320px
      panels:
        - title: Unit Tests Failure Rates (Check queue)
          span: 4
          targets:
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.pipeline.check.job.gate-neutron-python27-ubuntu-xenial.FAILURE),sum(stats_counts.zuul.pipeline.check.job.gate-neutron-python27-ubuntu-xenial.{SUCCESS,FAILURE})),'24hours'), 'gate-neutron-python27-ubuntu-xenial')
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.pipeline.check.job.gate-neutron-python34.FAILURE),sum(stats_counts.zuul.pipeline.check.job.gate-neutron-python34.{SUCCESS,FAILURE})),'24hours'), 'gate-neutron-python34')
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.pipeline.check.job.gate-neutron-python35.FAILURE),sum(stats_counts.zuul.pipeline.check.job.gate-neutron-python35.{SUCCESS,FAILURE})),'24hours'), 'gate-neutron-python35')
          type: graph
    - title: Graphs
      height: 320px
      panels:
        - title: Unit Tests Failure Rates (Gate queue)
          span: 4
          targets:
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.pipeline.gate.job.gate-neutron-python27-ubuntu-xenial.FAILURE),sum(stats_counts.zuul.pipeline.gate.job.gate-neutron-python27-ubuntu-xenial.{SUCCESS,FAILURE})),'24hours'), 'gate-neutron-python27-ubuntu-xenial')
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.pipeline.gate.job.gate-neutron-python34.FAILURE),sum(stats_counts.zuul.pipeline.gate.job.gate-neutron-python34.{SUCCESS,FAILURE})),'24hours'), 'gate-neutron-python34')
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.pipeline.gate.job.gate-neutron-python35.FAILURE),sum(stats_counts.zuul.pipeline.gate.job.gate-neutron-python35.{SUCCESS,FAILURE})),'24hours'), 'gate-neutron-python35')
          type: graph
    - title: Graphs
      height: 320px
      panels:
        - title: Periodic jobs
          span: 4
          targets:
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.pipeline.periodic.job.periodic-neutron-py27-with-oslo-master.FAILURE),sum(stats_counts.zuul.pipeline.periodic.job.periodic-neutron-py27-with-oslo-master.{SUCCESS,FAILURE})),'24hours'), 'periodic-neutron-py27-with-oslo-master')
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.pipeline.periodic.job.periodic-neutron-py34-with-oslo-master.FAILURE),sum(stats_counts.zuul.pipeline.periodic.job.periodic-neutron-py34-with-oslo-master.{SUCCESS,FAILURE})),'24hours'), 'periodic-neutron-py34-with-oslo-master')
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.pipeline.periodic.job.periodic-neutron-py34-with-neutron-lib-master.FAILURE),sum(stats_counts.zuul.pipeline.periodic.job.periodic-neutron-py34-with-neutron-lib-master.{SUCCESS,FAILURE})),'24hours'), 'periodic-neutron-py34-with-neutron-lib-master')
          type: graph
    - title: Graphs
      height: 320px
      panels:
        - title: Integrated Tempest Failure Rates (Gate queue)
          span: 4
          targets:
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.pipeline.gate.job.gate-tempest-dsvm-full-ubuntu-xenial.FAILURE),sum(stats_counts.zuul.pipeline.gate.job.gate-tempest-dsvm-full-ubuntu-xenial.{SUCCESS,FAILURE})),'24hours'), 'gate-tempest-dsvm-full-ubuntu-xenial')
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.pipeline.gate.job.gate-tempest-dsvm-neutron-full-ubuntu-xenial.FAILURE),sum(stats_counts.zuul.pipeline.gate.job.gate-tempest-dsvm-neutron-full-ubuntu-xenial.{SUCCESS,FAILURE})),'24hours'), 'gate-tempest-dsvm-neutron-full-ubuntu-xenial')
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.pipeline.gate.job.gate-neutron-dsvm-api{,-ubuntu-trusty,-ubuntu-xenial}.FAILURE),sum(stats_counts.zuul.pipeline.gate.job.gate-neutron-dsvm-api{,-ubuntu-trusty,-ubuntu-xenial}.{SUCCESS,FAILURE})),'24hours'), 'gate-neutron-dsvm-api')
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.pipeline.gate.job.gate-tempest-dsvm-neutron-dvr{,-ubuntu-trusty,-ubuntu-xenial}.FAILURE),sum(stats_counts.zuul.pipeline.gate.job.gate-tempest-dsvm-neutron-dvr{,-ubuntu-trusty,-ubuntu-xenial}.{SUCCESS,FAILURE})),'24hours'), 'gate-tempest-dsvm-neutron-dvr')
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.pipeline.gate.job.gate-tempest-dsvm-neutron-linuxbridge{,-ubuntu-trusty,-ubuntu-xenial}.FAILURE),sum(stats_counts.zuul.pipeline.gate.job.gate-tempest-dsvm-neutron-linuxbridge{,-ubuntu-trusty,-ubuntu-xenial}.{SUCCESS,FAILURE})),'24hours'), 'gate-tempest-dsvm-neutron-linuxbridge')
          type: graph
    - title: Graphs
      height: 320px
      panels:
        - title: Integrated Grenade Failure Rates (Gate queue)
          span: 4
          targets:
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.pipeline.gate.job.gate-grenade-dsvm-ubuntu-trusty.FAILURE),sum(stats_counts.zuul.pipeline.gate.job.gate-grenade-dsvm-ubuntu-trusty.{SUCCESS,FAILURE})),'24hours'), 'gate-grenade-dsvm-ubuntu-trusty')
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.pipeline.gate.job.gate-grenade-dsvm-multinode.FAILURE),sum(stats_counts.zuul.pipeline.gate.job.gate-grenade-dsvm-multinode.{SUCCESS,FAILURE})),'24hours'), 'gate-grenade-dsvm-multinode')
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.pipeline.gate.job.gate-grenade-dsvm-neutron.FAILURE),sum(stats_counts.zuul.pipeline.gate.job.gate-grenade-dsvm-neutron.{SUCCESS,FAILURE})),'24hours'), 'gate-grenade-dsvm-neutron')
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.pipeline.gate.job.gate-grenade-dsvm-neutron-multinode.FAILURE),sum(stats_counts.zuul.pipeline.gate.job.gate-grenade-dsvm-neutron-multinode.{SUCCESS,FAILURE})),'24hours'), 'gate-grenade-dsvm-neutron-multinode')
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.pipeline.gate.job.gate-grenade-dsvm-neutron-dvr-multinode.FAILURE),sum(stats_counts.zuul.pipeline.gate.job.gate-grenade-dsvm-neutron-dvr-multinode.{SUCCESS,FAILURE})),'24hours'), 'gate-grenade-dsvm-neutron-dvr-multinode')
          type: graph
    - title: Graphs
      height: 320px
      panels:
        - title: API/Functional/Fullstack Failure Rates/KeystoneV3 (Check queue)
          span: 4
          targets:
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.pipeline.check.job.gate-neutron-dsvm-api{,-ubuntu-trusty,-ubuntu-xenial}.FAILURE),sum(stats_counts.zuul.pipeline.check.job.gate-neutron-dsvm-api{,-ubuntu-trusty,-ubuntu-xenial}.{SUCCESS,FAILURE})),'24hours'), 'gate-neutron-dsvm-api')
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.pipeline.check.job.gate-neutron-dsvm-functional-ubuntu-trusty.FAILURE),sum(stats_counts.zuul.pipeline.check.job.gate-neutron-dsvm-functional-ubuntu-trusty.{SUCCESS,FAILURE})),'24hours'), 'gate-neutron-dsvm-functional-ubuntu-trusty')
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.pipeline.check.job.gate-neutron-dsvm-fullstack-ubuntu-trusty.FAILURE),sum(stats_counts.zuul.pipeline.check.job.gate-neutron-dsvm-fullstack-ubuntu-trusty.{SUCCESS,FAILURE})),'24hours'), 'gate-neutron-dsvm-fullstack-ubuntu-trusty')
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.pipeline.check.job.gate-tempest-dsvm-neutron-identity-v3-only-full-nv.FAILURE),sum(stats_counts.zuul.pipeline.check.job.gate-tempest-dsvm-neutron-identity-v3-only-full-nv.{SUCCESS,FAILURE})),'24hours'), 'gate-tempest-dsvm-neutron-identity-v3-only-full-nv')
          type: graph
    - title: Graphs
      height: 320px
      panels:
        - title: Functional/Fullstack Failure Rates (Experimental queue)
          span: 4
          targets:
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.pipeline.check.job.gate-neutron-dsvm-functional-ubuntu-xenial.FAILURE),sum(stats_counts.zuul.pipeline.check.job.gate-neutron-dsvm-functional-ubuntu-xenial.{SUCCESS,FAILURE})),'24hours'), 'gate-neutron-dsvm-functional-ubuntu-xenial')
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.pipeline.check.job.gate-neutron-dsvm-functional-py35-ubuntu-xenial.FAILURE),sum(stats_counts.zuul.pipeline.check.job.gate-neutron-dsvm-functional-py35-ubuntu-xenial.{SUCCESS,FAILURE})),'24hours'), 'gate-neutron-dsvm-functional-py35-ubuntu-xenial')
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.pipeline.check.job.gate-neutron-dsvm-fullstack-ubuntu-xenial.FAILURE),sum(stats_counts.zuul.pipeline.check.job.gate-neutron-dsvm-fullstack-ubuntu-xenial.{SUCCESS,FAILURE})),'24hours'), 'gate-neutron-dsvm-fullstack-ubuntu-xenial')
          type: graph
    - title: Graphs
      height: 320px
      panels:
        - title: DVR/LinuxBridge/Multi-node Failure Rates (Check queue)
          span: 4
          targets:
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.pipeline.check.job.gate-tempest-dsvm-neutron-full.FAILURE),sum(stats_counts.zuul.pipeline.check.job.gate-tempest-dsvm-neutron-full.{SUCCESS,FAILURE})),'24hours'), 'gate-tempest-dsvm-neutron-full')
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.pipeline.check.job.gate-tempest-dsvm-neutron-dvr{,-ubuntu-trusty,-ubuntu-xenial}.FAILURE),sum(stats_counts.zuul.pipeline.check.job.gate-tempest-dsvm-neutron-dvr{,-ubuntu-trusty,-ubuntu-xenial}.{SUCCESS,FAILURE})),'24hours'), 'gate-tempest-dsvm-neutron-dvr')
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.pipeline.check.job.gate-tempest-dsvm-neutron-linuxbridge{,-ubuntu-trusty,-ubuntu-xenial}.FAILURE),sum(stats_counts.zuul.pipeline.check.job.gate-tempest-dsvm-neutron-linuxbridge{,-ubuntu-trusty,-ubuntu-xenial}.{SUCCESS,FAILURE})),'24hours'), 'gate-tempest-dsvm-neutron-linuxbridge')
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.pipeline.check.job.gate-tempest-dsvm-neutron-multinode-full.FAILURE),sum(stats_counts.zuul.pipeline.check.job.gate-tempest-dsvm-neutron-multinode-full.{SUCCESS,FAILURE})),'24hours'), 'gate-tempest-dsvm-neutron-multinode-full')
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.pipeline.check.job.gate-tempest-dsvm-neutron-dvr-multinode-full.FAILURE),sum(stats_counts.zuul.pipeline.check.job.gate-tempest-dsvm-neutron-dvr-multinode-full.{SUCCESS,FAILURE})),'24hours'), 'gate-tempest-dsvm-neutron-dvr-multinode-full')
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.pipeline.check.job.gate-grenade-dsvm-neutron-multinode.FAILURE),sum(stats_counts.zuul.pipeline.check.job.gate-grenade-dsvm-neutron-multinode.{SUCCESS,FAILURE})),'24hours'), 'gate-grenade-dsvm-neutron-multinode')
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.pipeline.check.job.gate-grenade-dsvm-neutron-dvr-multinode.FAILURE),sum(stats_counts.zuul.pipeline.check.job.gate-grenade-dsvm-neutron-dvr-multinode.{SUCCESS,FAILURE})),'24hours'), 'gate-grenade-dsvm-neutron-dvr-multinode')
          type: graph
    - title: Graphs
      height: 320px
      panels:
        - title: LBaaS Failure Rates
          span: 4
          targets:
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.pipeline.check.job.gate-neutron-lbaasv2-dsvm-minimal.FAILURE),sum(stats_counts.zuul.pipeline.check.job.gate-neutron-lbaasv2-dsvm-minimal.{SUCCESS,FAILURE})),'24hours'), 'gate-neutron-lbaasv2-dsvm-minimal (check)')
          type: graph
    - title: Graphs
      height: 320px
      panels:
        - title: Rally Failure Rates
          span: 4
          targets:
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.pipeline.check.job.gate-rally-dsvm-neutron-neutron.FAILURE),sum(stats_counts.zuul.pipeline.check.job.gate-rally-dsvm-neutron-neutron.{SUCCESS,FAILURE})),'24hours'), 'gate-rally-dsvm-neutron-neutron (check)')
          type: graph

