dashboard:
  title: "OpenStack-Ansible"
  rows:
    - title: Description
      height: 100px
      panels:
        - title: Description
          content: |
            **This dashboard is managed by [Grafyaml](http://docs.openstack.org/infra/system-config/grafyaml.html).**

            If you would like to make changes to this dashboard, please see the grafana directory in [project-config](https://git.openstack.org/cgit/openstack-infra/project-config/tree/grafana/openstack-ansible.yaml).
          type: text
    - title: openstack-ansible check job runtimes
      showTitle: true
      height: 300px
      panels:
        - title: openstack-ansible-openstack-ansible-deploy-aio_lxc-ubuntu-xenial
          type: graph
          span: 3
          leftYAxisLabel: "time"
          y_formats:
            - s
            - none
          targets:
            - target: alias(scale(averageSeries(stats.timers.zuul.tenant.openstack.pipeline.check.project.git_openstack_org.openstack_openstack-ansible.master.job.openstack-ansible-deploy-aio_lxc-ubuntu-xenial.{SUCCESS,FAILURE}.mean), '0.001'), 'Average')
        - title: openstack-ansible-openstack-ansible-deploy-aio_lxc-ubuntu-bionic
          type: graph
          span: 3
          leftYAxisLabel: "time"
          y_formats:
            - s
            - none
          targets:
            - target: alias(scale(averageSeries(stats.timers.zuul.tenant.openstack.pipeline.check.project.git_openstack_org.openstack_openstack-ansible.master.job.openstack-ansible-deploy-aio_lxc-ubuntu-bionic.{SUCCESS,FAILURE}.mean), '0.001'), 'Average')
    - title: openstack-ansible check job failures
      showTitle: true
      height: 300px
      panels:
        - title: openstack-ansible job failure rates (Check queue)
          type: graph
          span: 12
          targets:
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.tenant.openstack.pipeline.check.project.git_openstack_org.openstack_openstack-ansible.master.job.openstack-ansible-deploy-aio_lxc-ubuntu-xenial.FAILURE),sum(stats_counts.zuul.tenant.openstack.pipeline.check.project.git_openstack_org.openstack_openstack-ansible.master.job.openstack-ansible-deploy-aio_lxc-ubuntu-xenial.{SUCCESS,FAILURE})),'24hours'), 'openstack-ansible-deploy-aio_lxc-ubuntu-xenial')
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.tenant.openstack.pipeline.check.project.git_openstack_org.openstack_openstack-ansible.master.job.openstack-ansible-deploy-aio_lxc-ubuntu-bionic.FAILURE),sum(stats_counts.zuul.tenant.openstack.pipeline.check.project.git_openstack_org.openstack_openstack-ansible.master.job.openstack-ansible-deploy-aio_lxc-ubuntu-bionic.{SUCCESS,FAILURE})),'24hours'), 'openstack-ansible-deploy-aio_lxc-ubuntu-bionic')
