dashboard:
  title: "OpenStack-Ansible"
  rows:
    - title: Description
      height: 100px
      panels:
        - title: Description
          content: |
            **This dashboard is managed by [Grafyaml](http://docs.openstack.org/infra/system-config/grafyaml.html).**

            If you would like to make changes to this dashboard, please see the grafana directory in [project-config](https://git.openstack.org/cgit/openstack-infra/project-config/tree/grafana/openstack-ansible.yaml).
          type: text
    - title: Ubuntu openstack-ansible check job runtimes
      showTitle: true
      height: 300px
      panels:
        - title: openstack-ansible-openstack-ansible-deploy-aio_lxc-ubuntu-xenial
          type: graph
          span: 3
          leftYAxisLabel: "time"
          y_formats:
            - s
            - none
          targets:
            - target: alias(scale(averageSeries(stats.timers.zuul.tenant.openstack.pipeline.check.project.git_openstack_org.openstack_openstack-ansible.master.job.openstack-ansible-deploy-aio_lxc-ubuntu-xenial.{SUCCESS,FAILURE}.mean), '0.001'), 'Average')
        - title: openstack-ansible-openstack-ansible-deploy-aio_lxc-ubuntu-bionic
          type: graph
          span: 3
          leftYAxisLabel: "time"
          y_formats:
            - s
            - none
          targets:
            - target: alias(scale(averageSeries(stats.timers.zuul.tenant.openstack.pipeline.check.project.git_openstack_org.openstack_openstack-ansible.master.job.openstack-ansible-deploy-aio_lxc-ubuntu-bionic.{SUCCESS,FAILURE}.mean), '0.001'), 'Average')
    - title: CentOS/openSUSE openstack-ansible check job runtimes
      showTitle: true
      height: 300px
      panels:
        - title: openstack-ansible-openstack-ansible-deploy-aio_lxc-centos-7
          type: graph
          span: 3
          leftYAxisLabel: "time"
          y_formats:
            - s
            - none
          targets:
            - target: alias(scale(averageSeries(stats.timers.zuul.tenant.openstack.pipeline.check.project.git_openstack_org.openstack_openstack-ansible.master.job.openstack-ansible-deploy-aio_lxc-centos-7.{SUCCESS,FAILURE}.mean), '0.001'), 'Average')
        - title: openstack-ansible-openstack-ansible-deploy-aio_lxc-opensuse-423
          type: graph
          span: 3
          leftYAxisLabel: "time"
          y_formats:
            - s
            - none
          targets:
            - target: alias(scale(averageSeries(stats.timers.zuul.tenant.openstack.pipeline.check.project.git_openstack_org.openstack_openstack-ansible.master.job.openstack-ansible-deploy-aio_lxc-opensuse-423.{SUCCESS,FAILURE}.mean), '0.001'), 'Average')
        - title: openstack-ansible-openstack-ansible-deploy-aio_lxc-opensuse-150
          type: graph
          span: 3
          leftYAxisLabel: "time"
          y_formats:
            - s
            - none
          targets:
            - target: alias(scale(averageSeries(stats.timers.zuul.tenant.openstack.pipeline.check.project.git_openstack_org.openstack_openstack-ansible.master.job.openstack-ansible-deploy-aio_lxc-opensuse-150.{SUCCESS,FAILURE}.mean), '0.001'), 'Average')
    - title: openstack-ansible check job success rate
      showTitle: true
      height: 300px
      panels:
        - title: openstack-ansible job success rate (Check queue)
          type: graph
          span: 12
          targets:
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.tenant.openstack.pipeline.check.project.git_openstack_org.openstack_openstack-ansible.master.job.openstack-ansible-deploy-aio_lxc-ubuntu-xenial.SUCCESS),sum(stats_counts.zuul.tenant.openstack.pipeline.check.project.git_openstack_org.openstack_openstack-ansible.master.job.openstack-ansible-deploy-aio_lxc-ubuntu-xenial.{SUCCESS,FAILURE,TIMED_OUT})),'24hours'), 'openstack-ansible-deploy-aio_lxc-ubuntu-xenial')
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.tenant.openstack.pipeline.check.project.git_openstack_org.openstack_openstack-ansible.master.job.openstack-ansible-deploy-aio_lxc-ubuntu-bionic.SUCCESS),sum(stats_counts.zuul.tenant.openstack.pipeline.check.project.git_openstack_org.openstack_openstack-ansible.master.job.openstack-ansible-deploy-aio_lxc-ubuntu-bionic.{SUCCESS,FAILURE,TIMED_OUT})),'24hours'), 'openstack-ansible-deploy-aio_lxc-ubuntu-bionic')
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.tenant.openstack.pipeline.check.project.git_openstack_org.openstack_openstack-ansible.master.job.openstack-ansible-deploy-aio_lxc-centos-7.SUCCESS),sum(stats_counts.zuul.tenant.openstack.pipeline.check.project.git_openstack_org.openstack_openstack-ansible.master.job.openstack-ansible-deploy-aio_lxc-centos-7.{SUCCESS,FAILURE,TIMED_OUT})),'24hours'), 'openstack-ansible-deploy-aio_lxc-centos-7')
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.tenant.openstack.pipeline.check.project.git_openstack_org.openstack_openstack-ansible.master.job.openstack-ansible-deploy-aio_lxc-opensuse-423.SUCCESS),sum(stats_counts.zuul.tenant.openstack.pipeline.check.project.git_openstack_org.openstack_openstack-ansible.master.job.openstack-ansible-deploy-aio_lxc-opensuse-423.{SUCCESS,FAILURE,TIMED_OUT})),'24hours'), 'openstack-ansible-deploy-aio_lxc-opensuse-423')
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.tenant.openstack.pipeline.check.project.git_openstack_org.openstack_openstack-ansible.master.job.openstack-ansible-deploy-aio_lxc-opensuse-150.SUCCESS),sum(stats_counts.zuul.tenant.openstack.pipeline.check.project.git_openstack_org.openstack_openstack-ansible.master.job.openstack-ansible-deploy-aio_lxc-opensuse-150.{SUCCESS,FAILURE,TIMED_OUT})),'24hours'), 'openstack-ansible-deploy-aio_lxc-opensuse-150')
    - title: openstack-ansible check job failure rate
      showTitle: true
      height: 300px
      panels:
        - title: openstack-ansible job failure rate (Check queue)
          type: graph
          span: 12
          targets:
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.tenant.openstack.pipeline.check.project.git_openstack_org.openstack_openstack-ansible.master.job.openstack-ansible-deploy-aio_lxc-ubuntu-xenial.FAILURE),sum(stats_counts.zuul.tenant.openstack.pipeline.check.project.git_openstack_org.openstack_openstack-ansible.master.job.openstack-ansible-deploy-aio_lxc-ubuntu-xenial.{SUCCESS,FAILURE,TIMED_OUT})),'24hours'), 'openstack-ansible-deploy-aio_lxc-ubuntu-xenial')
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.tenant.openstack.pipeline.check.project.git_openstack_org.openstack_openstack-ansible.master.job.openstack-ansible-deploy-aio_lxc-ubuntu-bionic.FAILURE),sum(stats_counts.zuul.tenant.openstack.pipeline.check.project.git_openstack_org.openstack_openstack-ansible.master.job.openstack-ansible-deploy-aio_lxc-ubuntu-bionic.{SUCCESS,FAILURE,TIMED_OUT})),'24hours'), 'openstack-ansible-deploy-aio_lxc-ubuntu-bionic')
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.tenant.openstack.pipeline.check.project.git_openstack_org.openstack_openstack-ansible.master.job.openstack-ansible-deploy-aio_lxc-centos-7.FAILURE),sum(stats_counts.zuul.tenant.openstack.pipeline.check.project.git_openstack_org.openstack_openstack-ansible.master.job.openstack-ansible-deploy-aio_lxc-centos-7.{SUCCESS,FAILURE,TIMED_OUT})),'24hours'), 'openstack-ansible-deploy-aio_lxc-centos-7')
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.tenant.openstack.pipeline.check.project.git_openstack_org.openstack_openstack-ansible.master.job.openstack-ansible-deploy-aio_lxc-opensuse-423.FAILURE),sum(stats_counts.zuul.tenant.openstack.pipeline.check.project.git_openstack_org.openstack_openstack-ansible.master.job.openstack-ansible-deploy-aio_lxc-opensuse-423.{SUCCESS,FAILURE,TIMED_OUT})),'24hours'), 'openstack-ansible-deploy-aio_lxc-opensuse-423')
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.tenant.openstack.pipeline.check.project.git_openstack_org.openstack_openstack-ansible.master.job.openstack-ansible-deploy-aio_lxc-opensuse-150.FAILURE),sum(stats_counts.zuul.tenant.openstack.pipeline.check.project.git_openstack_org.openstack_openstack-ansible.master.job.openstack-ansible-deploy-aio_lxc-opensuse-150.{SUCCESS,FAILURE,TIMED_OUT})),'24hours'), 'openstack-ansible-deploy-aio_lxc-opensuse-150')
    - title: openstack-ansible check job timeout rate (Check queue)
      showTitle: true
      height: 300px
      panels:
        - title: openstack-ansible job timeout rate (Check queue)
          type: graph
          span: 12
          targets:
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.tenant.openstack.pipeline.check.project.git_openstack_org.openstack_openstack-ansible.master.job.openstack-ansible-deploy-aio_lxc-ubuntu-xenial.TIMED_OUT),sum(stats_counts.zuul.tenant.openstack.pipeline.check.project.git_openstack_org.openstack_openstack-ansible.master.job.openstack-ansible-deploy-aio_lxc-ubuntu-xenial.{SUCCESS,FAILURE,TIMED_OUT})),'24hours'), 'openstack-ansible-deploy-aio_lxc-ubuntu-xenial')
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.tenant.openstack.pipeline.check.project.git_openstack_org.openstack_openstack-ansible.master.job.openstack-ansible-deploy-aio_lxc-ubuntu-bionic.TIMED_OUT),sum(stats_counts.zuul.tenant.openstack.pipeline.check.project.git_openstack_org.openstack_openstack-ansible.master.job.openstack-ansible-deploy-aio_lxc-ubuntu-bionic.{SUCCESS,FAILURE,TIMED_OUT})),'24hours'), 'openstack-ansible-deploy-aio_lxc-ubuntu-bionic')
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.tenant.openstack.pipeline.check.project.git_openstack_org.openstack_openstack-ansible.master.job.openstack-ansible-deploy-aio_lxc-centos-7.TIMED_OUT),sum(stats_counts.zuul.tenant.openstack.pipeline.check.project.git_openstack_org.openstack_openstack-ansible.master.job.openstack-ansible-deploy-aio_lxc-centos-7.{SUCCESS,FAILURE,TIMED_OUT})),'24hours'), 'openstack-ansible-deploy-aio_lxc-centos-7')
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.tenant.openstack.pipeline.check.project.git_openstack_org.openstack_openstack-ansible.master.job.openstack-ansible-deploy-aio_lxc-opensuse-423.TIMED_OUT),sum(stats_counts.zuul.tenant.openstack.pipeline.check.project.git_openstack_org.openstack_openstack-ansible.master.job.openstack-ansible-deploy-aio_lxc-opensuse-423.{SUCCESS,FAILURE,TIMED_OUT})),'24hours'), 'openstack-ansible-deploy-aio_lxc-opensuse-423')
            - target: alias(movingAverage(asPercent(transformNull(stats_counts.zuul.tenant.openstack.pipeline.check.project.git_openstack_org.openstack_openstack-ansible.master.job.openstack-ansible-deploy-aio_lxc-opensuse-150.TIMED_OUT),sum(stats_counts.zuul.tenant.openstack.pipeline.check.project.git_openstack_org.openstack_openstack-ansible.master.job.openstack-ansible-deploy-aio_lxc-opensuse-150.{SUCCESS,FAILURE,TIMED_OUT})),'24hours'), 'openstack-ansible-deploy-aio_lxc-opensuse-150')
