- hosts: all
  roles:
    - fetch-output
    - merge-output-to-logs

- hosts: localhost
  roles:
    - role: add-fileserver
      when:
        - zuul_success | bool
        - zuul.change is not defined

- hosts: "{{ fileserver.fqdn }}"
  gather_facts: False
  roles:
    - role: publish-artifacts-to-fileserver
      when:
        - zuul_success | bool
        - zuul.change is not defined

- hosts: all
  # NOTE(pabelanger): We ignore_errors for the following tasks as not to fail
  # successful jobs.
  ignore_errors: yes
  roles:
    - remove-build-sshkey
