- hosts: localhost
  roles:
    - role: emit-job-header
      zuul_log_url: "http://logs.openstack.org"

- hosts: all
  roles:
    - add-build-sshkey
    - start-zuul-console
    - configure-unbound
    - validate-host
    - use-cached-repos
    - mirror-workspace-git-repos
    - mirror-info
    - configure-mirrors
