- hosts: localhost
  roles:
    - role: emit-job-header
      zuul_log_url: "http://logs.openstack.org"

- hosts: all
  roles:
    - add-build-sshkey
    - start-zuul-console
    - use-cached-repos
    - mirror-workspace-git-repos
    - role: validate-host
      # TODO(mordred) When we have site-local variables, these should go there
      zuul_traceroute_host: git.openstack.org
      zuul_image_manifest: /etc/dib-builddate.txt
    - role: configure-mirrors
      mirror_fqdn: "{{ zuul_site_mirror_fqdn }}"
