- hosts: all
  roles:
    - role: bindep
      bindep_profile: test
      bindep_dir: "src/{{ zuul.project.canonical_name }}"
    - legacy-install-afs-with-puppet
    - legacy-copy-project-config-scripts

  pre_tasks:
    # NOTE(pabelanger): Manually install EPEL dependencies as not to keep EPEL
    # enabled.
    - name: Manually install EPEL dependencies
      become: yes
      yum:
        name: "{{ item }}"
        enablerepo: epel
        state: present
      when: ansible_distribution == "CentOS"
      with_items:
        - dkms
        - kstart
        - parallel
