- hosts: localhost
  roles:
    - role: create-afs-token
    - role: release-afs-volume
      afs_volume: trustyx64
    - role: release-afs-volume
      afs_volume: cent7x64
    - role: release-afs-volume
      afs_volume: xenialx64
    - role: destroy-afs-token
