- hosts: localhost
  roles:
    - create-afs-token
    - role: release-afs
      afs_volume: trustyx64
    - role: release-afs
      afs_volume: cent7x64
    - role: release-afs
      afs_volume: xenialx64
    - destroy-afs-token
