- name: Select python version to build
  set_fact:
    wheel_python: "python{{ inventory_hostname[-1] }}"

- name: Ensure wheel dir exists
  file:
    group: zuul
    owner: zuul
    path: "{{ wheel_dir }}"
    state: directory
  become: yes

- name: Build the wheel mirror
  shell:
    cmd: ./scripts/wheel-build.sh {{ wheel_dir }} {{ wheel_python }}
    executable: /bin/bash
  # ANSIBLE0013 complains about shell. TODO(jaegerandi): Use command instead,
  # for now we just silence the warning.
  tags:
    - skip_ansible_lint
