- name: Select python version to build
  set_fact:
    wheel_python: "python{{ inventory_hostname[-1] }}"

- name: Ensure wheel dir exists
  file:
    path: "{{ wheel_dir }}"
    state: directory
  become: yes

- name: Build the wheel mirror
  shell: bash -x scripts/wheel-build.sh {{ wheel_dir }} {{ wheel_python }}
