- hosts: all
  pre_tasks:
    - name: Install git-review
      command: pip install git-review
      become: yes
  roles:
    - role: configure-git
      git_config:
        user.name: OpenStack Proposal Bot
        user.email: openstack-infra@lists.openstack.org
        gitreview.username: proposal-bot
    - legacy-copy-project-config-scripts
    - copy-proposal-common-scripts
    - add-sshkey
    - bindep
    - ensure-tox
