- hosts: all
  pre_tasks:
    - name: Install git-review
      command: pip install git-review
      become: yes
  roles:
    - legacy-copy-project-config-scripts
    - add-sshkey
    - role: bindep
      bindep_profile: test
      bindep_dir: "{{ zuul.project.src_dir }}"
    - ensure-tox
