- hosts: all
  roles:
    - role: write-root-marker
      root_marker_dir: "src/{{ zuul.project.canonical_name }}/doc/build/html"
      when: zuul_success | bool
    - role: fetch-sphinx-output
      sphinx_output_src: "src/{{ zuul.project.canonical_name }}/doc/build/html/"
      zuul_executor_dest: "{{ zuul.executor.work_root }}/artifacts"
      when: zuul_success | bool
