- name: Copy the wheels to AFS
  script: wheel-copy.sh {{ wheel_dir }} {{ afs_dir }}

- name: Rebuild top-level mirror index
  script: wheel-index.sh {{ afs_dir }}
  # With multiple python2/3 builds, we only need one host to generate
  # the final index.  All hosts should be finished copying under
  # linear strategy.
  run_once: True

- name: Get project directories
  # the directories are laid out a/ b/ c/ ... z/ with projects
  # underneath (ergo */* match).  We actually use mod_rewrite to paper
  # over this in the mirror apache config for external users.
  shell: 'ls -d {{ afs_dir }}/*/*'
  register: directories

- name: Create individual project indexes
  # NOTE(ianw) .test to be removed after testing
  script: wheel-indexer.py --debug index.html.test
  args:
    chdir: '{{ item }}'
    executable: 'python3'
  loop: "{{ directories.stdout.split('\n') }}"
  # NOTE(ianw) remove after testing
  ignore_errors: true
